on:
  push:
    branches: [ci-test]

jobs:
  benchmark:
    name: Collect performance data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run benchmark
        run: cargo +nightly bench | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: RustPython Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
