on:
  push:
    branches: [ci-test]

name: Benchmark

jobs:
  benchmark:
    name: Collect performance data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout previouse performance data
        uses: actions/checkout@v2
        with:
          repository: skinny121/rustpython.github.io
          ssh-key: ${{ secrets.ACTIONS_TESTS_DATA_DEPLOY_KEY }}
          path: website
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run benchmark
        run: cargo +nightly bench | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: RustPython Benchmarks
          tool: 'cargo'
          output-file-path: output.txt
          external-data-json-path: website/_data/perf_results.json
      - name: Upload performance data to the website
        run: |
          cd website
          git add ./_data/perf_results.json
          git -c user.name="Github Actions" -c user.email="actions@github.com" commit -m "Update regression test results"
          git push
